### ISSUE TITLE
AddonSignals fails on Python 3.5

### ISSUE THREAD

**Issue by dagwieers** [ruuk/script.module.addon.signals#7]
There is a known issues on Python 3 with Python 3.5 and older causing `json.loads()` to fail on **bytes** or **bytestring**.

This issue came up when performing unit tests on AddonSignals.
See: https://travis-ci.org/dagwieers/service.upnext/builds/616895177

```
$ coverage run -p -m unittest discover
...E
======================================================================
ERROR: test_to_addon_signals (test.test_encoding.TestEncoding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dagwieers/service.upnext/test/test_encoding.py", line 71, in test_to_addon_signals
    decoded_data = AddonSignals._decodeData('["%s"]' % encoded_data)  # pylint: disable=protected-access
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/AddonSignals.py", line 21, in _decodeData
    return json.loads(base64.b64decode(data[0]))
  File "/opt/python/3.5.6/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
----------------------------------------------------------------------
Ran 4 tests in 0.004s
FAILED (errors=1)
```

**Comment by dagwieers** [comment]
I added PR #8 with unit tests which trigger the same issue on Python 3.5.
See: https://travis-ci.org/dagwieers/script.module.addon.signals/builds/616974505
